import LegalLayout from "../components/LegalLayout.jsx";

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" updated="August 26, 2026">

      <Section title="1. Acceptance of terms">
        <p>
          By creating an account or using Afterword ("the Service"), you agree
          to these Terms of Service. If you don't agree, please don't use the
          Service.
        </p>
      </Section>

      <Section title="2. What the Service does">
        <p>
          Afterword lets you draft emails manually or with AI assistance, and
          schedule them to be sent from your own Gmail account at a future
          time you choose, via the Gmail API.
        </p>
      </Section>

      <Section title="3. Your Google account & sending emails">
        <List
          items={[
            "You authorize Afterword to send email on your behalf, only for the messages you explicitly compose and schedule within the app.",
            "You are responsible for the content of every email you draft or schedule, whether written by you or generated with AI assistance — review AI-generated drafts before scheduling them.",
            "You can revoke this authorization at any time via your Google Account permissions page; doing so will prevent any pending scheduled emails from being sent.",
          ]}
        />
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <List
          items={[
            "Send spam, unsolicited bulk email, phishing, or malicious content.",
            "Impersonate another person or misrepresent your affiliation.",
            "Violate any applicable law or third party's rights.",
            "Attempt to disrupt, reverse-engineer, or abuse the Service or its infrastructure.",
          ]}
        />
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these terms.
        </p>
      </Section>

      <Section title="5. AI-generated content">
        <p>
          Draft content generated by the AI drafting feature is produced by a
          third-party model (Google Gemini) based on the instructions you
          provide. We don't guarantee its accuracy, tone, or appropriateness —
          you're responsible for reviewing and editing any AI-generated draft
          before it's sent.
        </p>
      </Section>

      <Section title="6. Scheduled sending">
        <p>
          We aim to send scheduled emails at the exact time you select, but we
          don't guarantee delivery at that precise instant — network issues,
          Google API availability, or revoked permissions can delay or prevent
          a send. If a scheduled send fails, it will be marked as failed in
          your dashboard rather than retried indefinitely.
        </p>
      </Section>

      <Section title="7. Availability">
        <p>
          The Service is provided "as is" without warranties of any kind. We
          don't guarantee uninterrupted or error-free operation.
        </p>
      </Section>

      <Section title="8. Limitation of liability">
        <p>
          To the fullest extent permitted by law, [Your Company / Your Name]
          is not liable for indirect, incidental, or consequential damages
          arising from your use of the Service, including emails sent, not
          sent, or sent with content you did not intend.
        </p>
      </Section>

      <Section title="9. Changes to the Service or these terms">
        <p>
          We may update these terms or change the Service over time. Continued
          use after changes take effect means you accept the updated terms.
        </p>
      </Section>

      <Section title="10. Termination">
        <p>
          You may stop using the Service and delete your account at any time
          by contacting [your-email@example.com]. We may suspend or terminate
          access for violation of these terms.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>Questions about these terms: chbaraheem787@gmail.com</p>
      </Section>
    </LegalLayout>
  );
}

function Section({ title, children }) {
  return (
    <section>
      <h2 className="font-display text-xl mb-3 text-ink">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function List({ items }) {
  return (
    <ul className="list-disc pl-5 space-y-1.5">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  );
}

function Callout({ children }) {
  return (
    <div className="bg-brass/10 border border-brass/30 text-ink/70 text-sm rounded-sm px-4 py-3">
      {children}
    </div>
  );
}
